### PR TITLE
Switch to sphinxcontrib-prettyproof

### PR DESCRIPTION
**Pull request by mmcky**
**Status: In-Work**

This PR will switch to use [sphinxcontrib-prettyproof](https://github.com/najuzilu/sphinxcontrib-prettyproof) and is used as a testing branch.

### CODE REVIEW

**Comment by jstac** [comment]
Did I goof up or is adding cached execution manual and not the default?  

If so, should we change that default in JB?

**Comment by AakashGfude** [comment]
@jstac , yes it is not the default, as was suggested by Chris. H. As we wanted `jupyter-cache` to become more stable. But, I think it has become stable enough?

**Comment by jstac** [comment]
My vote is to add it and then deal with problems as they come up.

**Comment by mmcky** [comment]
@jstac this is looking pretty good with the latest `master` version of [sphinxcontrib-prettyproof](https://github.com/najuzilu/sphinxcontrib-prettyproof) that Juna merged this morning. Aakash is just going to clean up the test in `memoryless` (in commit history) and this should be good to go. A few undefined label warnings but will check those out in the source.

**Comment by AakashGfude** [comment]
Done @mmcky

**Comment by mmcky** [comment]
@AakashGfude for this case in `generators.md`

````
```{proof:lemma} Differentiability of the exponential map
:label: diffexpmap

For all $A \in \linop$, the map $t \mapsto e^{tA}$ is everywhere differentiable and 

$$
    \frac{d}{dt} e^{tA} = e^{tA} A = A e^{tA}
$$ (expdiffer)
```
````

would this math be referenced normally as a math reference or via `proof:ref`. I suspect the former. @jstac do you want to reference the equation within the `lemma`?

**Comment by jstac** [comment]
The former --- it will be referenced as {eq}`expdiffer`.

Is it problematic to have it in the lemma environ?

**Comment by mmcky** [comment]
hey @jstac just tested this and 

````
{eq}`expdiffer`
````

works well. The warnings are that it is currently being used for a `{proof:ref}` reference in Exercise1

**Comment by mmcky** [comment]
the current `warnings` should all be resolvable in `source` such as heading alignment in `generators.md` file. I can push adjustments if you like -- but they look like they are being edited so aren't final docs.

**Comment by mmcky** [comment]
@jstac there is really only one small change re: execution config. so feel free to close this PR and add it in when you like.

**Comment by jstac** [comment]
Hmmm, still getting value error.

On version 0.2 of prettyproof, 0.7.5 of JB.

Would you mind to pull my changes and try again?

**Comment by jstac** [comment]
Value error disappears when I switch back to sphinxcontrib.proof

**Comment by mmcky** [comment]
hey @jstac I think becuase a new version number hasn't been set the install doesn't actually update `sphinxcontrib-prettyproof`. To upgrade manually from master I had to:

```
pip uninstall sphinxcontrib-prettyproof
python setup.py install
```

**Comment by jstac** [comment]
Thanks @mmcky, much appreciated.  Closing.

**Pull request closed without merging**
