### PR TITLE
md1_update_E()_to_Exp()

### PR DESCRIPTION
**Pull request by shlff**
Morning @jstac , in lecture [memoryless_distribution](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/memoryless.md#memoryless-distributions), I updated the notation for an exponential distribution with parameter lamba from  to  to keep consistent with the notation in later lectures and [Wikipedia](https://en.wikipedia.org/wiki/Exponential_distribution).

In addition, I added ``, denoted by $Exp(\lambda)$`` in the definition of exponential distribution to clarify it. Please see [here](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/memoryless.md#the-exponential-distribution).

### CODE REVIEW

**Comment by jstac** [comment]
Thanks @shlff , good catch.

This should have "Exp" as text font rather than math font.  (This is a general rule, as we see with "max" and "min".)

@mmcky, in LaTeX I would achieve this with "\DeclareMathOperator{\Exp}{Exp}".  Is there any way to inject this into a preamble included somewhere in the doc that's see by mathjax?

Apparently this is supported, now that I check: http://docs.mathjax.org/en/latest/input/tex/macros/.  Can you think how I would include this in the document?

**Comment by mmcky** [comment]
hey @jstac -- just yesterday identified that `LaTeX` preamble wasn't making it through `jb` -- I will check on the `html` side for custom mathjax settings.

**Comment by mmcky** [comment]
hey @jstac and @shlff -- there is [a mechanism for defining TeX macros for mathjax](https://jupyterbook.org/advanced/sphinx.html#defining-tex-macros) but that mechanism doesn't seem to work at the moment in `jupyter-book`. I have raised a [bug report](https://github.com/executablebooks/jupyter-book/issues/909)

**Comment by mmcky** [comment]
hey @jstac is this the rendering you're after for `Exp` as text

Screen Shot 2020-08-26 at 1 52 49 pm

**Comment by jstac** [comment]
Yes `:-)`

**Comment by mmcky** [comment]
Doh - just tried to push a `commit` to this PR to fix this but don't have write access `:-(`

**Comment by mmcky** [comment]
@shlff I updated many of the `Exp` with `\Exp` so that the new mathjax config will use `text` fonts via macros. Would you mind to review the diff and check I haven't:

1. promoted an `exp` to `Exp`
1. missed adding a `\` to an `Exp`

Thanks. 

Once the next version of `myst_parser` comes out we can remove the

```
myst_override_mathjax: false
```

**Comment by shlff** [comment]
Thanks @mmcky , I checked all ``exp`` and ``Exp`` in the lecture ``memoryless_distribution`` and can confirm that you
1. did not promote an ``exp`` to ``Exp``,
2. did not miss adding a ``\`` to an ``Exp``.

Thanks for your excellent job.

**Comment by jstac** [comment]
Many thanks @shlff and @mmcky .  I'll merge now and then test locally.

(I should do the reverse but I'm lazy :grimacing: )

**Comment by mmcky** [comment]
roger that -- let me know if you run into any trouble building @jstac

**Pull request merged**
